### ISSUE TITLE
extension removes s from submit inthe url to be resized on saving

### ISSUE THREAD

**Issue by moonoo** [klaftertief-symphony/imagecropper#1]
I have encountered this bug using Symphony 2.0.4 that might stop the Image Crop field from working correclty for me...

Whenever I click on the image itself to perform a crop or use the slider for size scaling.. when I look at the produced URL below the "Resize proportionally after cropping" field.. It seem to remove the "s" from the "submitted" part of the url so I end up with this:

http://localhost/image/4/320/320/663/294/104/0/ubmitted/images/myimage.jpg

This will not work as It's an invalid url and will throw a wobbly as to the location of the file I'm guessing.. just noticed it today but wondering if this is isolated or in fact a bug?

**Comment by klaftertief** [comment]
This functionality is removed.
