### ISSUE TITLE
Compatibility with Symphony 2.2.5

### ISSUE THREAD

**Issue by madaerodog** [klaftertief-symphony/imagecropper#13]
I have the above mentioned Symphony version installed and I want to use the image cropper extension but I get a lot of errors from the modified JIT extension that is required for it to function. Any idea when this is will be updated to work with the current version of Symphony?

**Comment by madaerodog** [comment]
here is one error that I am getting Fatal error: Undefined class constant 'kERROR' in /extensions/jit_image_manipulation/lib/image.php on line 85

**Comment by madaerodog** [comment]
It seems I was using the master branch of the JIT extension rather than the jcrop branch, so it works now!

**Comment by klaftertief** [comment]
Sorry for not responding. Glad you worked it out.
