### ISSUE TITLE
Cropping area doesn't appear when views in SBL+

### ISSUE THREAD

**Issue by vlad-ghita** [klaftertief-symphony/imagecropper#15]
If I'm viewing an entry with Image Cropper in a SBL+ modal, the cropped area doesn't appear.

The assets are appear in the iframe `head` but nothing happens.

Thanks.

**Comment by klaftertief** [comment]
Thanks for reporting. I've never used the SBL+ (installed in once), so it's not a top priority for me. Might need some time to fix.

Are there any errors in the JS console?

**Comment by vlad-ghita** [comment]
No errors in console.

I would debug it if I only knew how it works :)

**Comment by vlad-ghita** [comment]
Ok, steps to reproduce:

Take `Photo albums` and `Images` sections joined by a SBL+ in `Photo albums` to `Images`.
1. Open a `Photo albums` entry.
2. Click to edit an `Image` -> jCrop fails
3. Close modal
4. Click again to edit _any_ `Image`. -> jCrop works

Probably the assets are not loading fast enough? Or ...
