### ISSUE TITLE
Ability to have decimal ratio's

### ISSUE THREAD

**Issue by brendo** [klaftertief-symphony/imagecropper#3]
Sometimes I've found the ratios design come up with aren't 'whole numbers'.

It would be nice if I could add these to the Settings, ie. `1/1.8`

At the moment the error returned is `Ratios have to be well formed.`

**Comment by klaftertief** [comment]
Yes, dividend and divisor need to be whole numbers. Do you think supporting `1/1.8` is better than using `10/18` (or `5/9`)?

**Comment by brendo** [comment]
Heh, suppose not, thanks again :)

**Comment by klaftertief** [comment]
So I don't see a reason to change the behavior at the moment. Unless you convince me.
