### ISSUE TITLE
Maximum Width/Height

### ISSUE THREAD

**Issue by brendo** [klaftertief-symphony/imagecropper#4]
I know there are currently settings for a minimum width/height, but it'd be great if there could maximum values as well!

**Comment by klaftertief** [comment]
There was the support for maximum dimensions in an earlier version. I removed it because you can always scale the image down to a maximum size in the frontend using JIT.

What is the use case?

**Comment by brendo** [comment]
That's very true, I totally forgot you could scale on the frontend.

Our use case is the design offers an area that provides 235 x 115 images and our previous automatically crop and scale technique (using Rowan's image-jit) often cropped out the 'wrong' part of the image. It's of no fault of the extension, because the client would upload all sorts of differently sized images and expect it to know to crop to the focal point.

Using imagecropper allows them to select that area, but they can be cheeky and just expand it to be the whole image which leds us to the same problem. At the moment I can't lock the ratio either (related to #1) as 235x115 isn't a normal ratio.

**Comment by klaftertief** [comment]
So do you need the max settings? It's not hard to implement, because it's supported by jCrop.

**Comment by klaftertief** [comment]
Bump.

**Comment by brendo** [comment]
I'm unsure now. A user might want to select a large area and have it scaled to the max size, or they may want to only select a set dimension and have it scale down (via the frontend) to the max size.

**Comment by klaftertief** [comment]
I thought about this and I think that a maximum dimension isn't necessary or even doesn't make sense. When you set a maximum dimension and a user uploads an image that is larger, the user isn't free to select any area he wants. The image itself sets the max dimension. In your example above you would set the minimum dimension to 235w and115h and the ratio to 235/115. Any image with a larger selection just gets scaled down in the frontend.

It will be much clearer for the user when she can preview the image how it will be shown in the frontend. So a solution is the additional preview setting described in issue #5.
