### ISSUE TITLE
Image Cropper doesn't support 'Advanced Upload Field' anymore

### ISSUE THREAD

**Issue by brendo** [klaftertief-symphony/imagecropper#6]
It's not the extensions fault, but the Advanced Upload Field has been updated by Rowan to the confusing 'Upload Field'. The issue here is his 'Upload Field' has a different markup to what the imagecropper Javascript expects, so the `No image found. Please upload an image and save entry.` always appears on the displayPublishPanel.

I know this is a relatively difficult and annoying issue to solve, as the real Upload Field and the renamed Upload Field have different markup, but it'd be nice if you had any ideas?

**Comment by klaftertief** [comment]
Will look into it.

**Comment by klaftertief** [comment]
I couldn't install the 'Advanced Upload Field' without messing with my installation, so could you please check if the development branch fixes this problem?

I was able to remove the dependency from the markup to check if there is an uploaded image, but I had to change the logic for the "Remove File"/Clear File" link. Does removing a file clear the cropper? I had to add a separate selector for the 'Advanced Upload Field', but I think it's not too much of a dependency.

**Comment by klaftertief** [comment]
Can you confirm that this is working? I updated the extension today but didn't include this commit, but I'm happy to release another new version when it's working.
