### ISSUE TITLE
`displayPublishPanel`

### ISSUE THREAD

**Issue by brendo** [klaftertief-symphony/imagecropper#7]
I noticed going over the code that the `displayPublishPanel` function uses it's own logic to get the current `entry_id` using the `getPageCallback` function.

This is not necessary, the `displayPublishPanel` functions accepts a 6th parameter, `$entry_id` that will return the current `entry_id` or null if it is a new entry.

**Comment by klaftertief** [comment]
Thanks for reporting. Will update the extension in the next couple of days.
