### ISSUE TITLE
minimum width/height (sorta) not being adhered to

### ISSUE THREAD

**Issue by fawx** [klaftertief-symphony/imagecropper#8]
when an image is uploaded that is larger than the cropping control area, pixels are sometimes fractioned in such a way that allows the user to go below the minimum dimension size.

[example](http://hairb.us/p/imagecropper.jpg)

**Comment by klaftertief** [comment]
It seems like Jcrop returns wrongly rounded coordinates. So this should be fixed in Jcrop itself, but I'll check for the minimum dimension before saving in the ImageCropper itself.
