### ISSUE TITLE
Issue with Subsection Manager 1.2

### ISSUE THREAD

**Issue by davjand** [klaftertief-symphony/imagecropper#9]
Not sure if this is a problem here or a problem subsection manager but subsection manager tries to access 

``` php
prepareTableValue($data)
```

Which generates an error

It can be fixed by adding the below into the field class

``` php
function preparePlainTextValue($data,$entry_id){
   return $this->prepareTableValue($data,NULL,$entry_id);
}
```

**Comment by klaftertief** [comment]
Thanks for reporting.
This was a [known issue](http://symphony-cms.com/discuss/thread/41680/2/#position-26) which is fixed with this commit.
